sudo: false
git:
  depth: 1
language: php
matrix:
  fast_finish: true
  include:
  - php: 5.5
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 5.5
  - php: 5.6
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 5.6
    env: PHPUNIT_COVERAGE="--coverage-clover=coverage.xml"
  - php: 7.0
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 7.0
  - php: 7.1
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 7.1
  - php: nightly
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: nightly
  allow_failures:
  - php: nightly
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: nightly
cache:
  directories:
  - "$HOME/.composer/cache"
before_install:
- stty cols 120
- |
  if [ -z "$PHPUNIT_COVERAGE" ]; then
      phpenv config-rm xdebug.ini || true
  fi
install:
- composer self-update
- composer config -g repositories.asset-packagist composer https://asset-packagist.org
- travis_retry composer update --no-interaction --prefer-stable --prefer-dist $COMPOSER_LOWEST
- composer show
script:
- vendor/bin/phpunit $PHPUNIT_COVERAGE
after_success:
- |
  if [ -n "$PHPUNIT_COVERAGE" ]; then
      travis_retry wget https://codecov.io/bash
      bash ./bash
  fi
after_script:
- |
  if [ -n "$PHPUNIT_COVERAGE" ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
  fi
notifications:
  slack:
    on_start: always
    on_pull_requests: false
    rooms:
    - secure: Dc8GaG4r/oRnzOz4l95fsW7Dp+HACu2vbyEaORuRvWt4KpR+Qn2mDn0cejA9FxHU4j+/D8XuJlhSf0E0YW3KCvsJkhlOZ7Yrj/H1qxDCoUvPoptdHLN2YIpBbj+CSTmfGebihD4OODDwB2F7iGpDJzENTWDhZ6FM8Coa/3Kf4wJha4GQkoxlNFA1rEzw3C4nfRqtF+kIf1ogt1cXZU4xSPtkYnTcXM0IPWKB+XYEKZCZKpzYSGNkGre9dd0v4B4pxzFrUxmH6yGX3IeiSQmIlQWXm8QgdD7Z71bS1Qri6zaXkof0cNsmFPG+vxazXj6MVPUhT3b1vcserDGv2nIqOMPvmEqn+y6cP+DWHCpibSPCQXaiCaol4BT5hQe1aUoIaeLJAsRauLeMr1UR/VeX8co5m5kaKNUiM5kYZ84+8tTihelYrFXhW1JkU51nCIPHjsRCl9ElA1yrNw9O90yLl8kJBXQfcFzRsd2mxjTg/AXOL11xXh5o6mntJ8Xyoos6MI2VXDvoOMbhFvPLK9R6sZn+FTITQVx1wryzX6+jaOMiC9gSfu6FVAnqDKtbsrINAyYNN7dje+9JCEwaM//GdyACA3wgL6jdZw03+yQUsnEERgDO/MqvLMdF63+/cpqrKksN/pQMxcXvHFFEysI6GkFvT/GuB01I9oc0iZi1W/c=
